# Generated by Django 3.2.11 on 2022-04-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('audience', models.IntegerField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('genre', models.CharField(max_length=30)),
                ('score', models.FloatField(null=True)),
                ('poster_url', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
