# Generated by Django 3.2.11 on 2022-04-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('액션', '액션'), ('스릴러', '스릴러'), ('코미디', '코미디'), ('SF', 'SF'), ('로맨스', '로맨스')], max_length=30),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
