# Generated by Django 3.2.12 on 2022-05-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
    ]
